# Generated by Django 5.1.1 on 2024-11-15 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0002_remove_societyadmin_admin_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society',
            name='slug',
        ),
    ]
