# Generated by Django 5.1.1 on 2024-11-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0004_membershipapplication_membershiprequest_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_member_specific',
            field=models.BooleanField(default=False),
        ),
    ]
