# Generated by Django 5.1.1 on 2024-11-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0007_event_video_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
        model_name='event',
        name='venue',
     field=models.CharField(default='Unknown Venue', max_length=255),
    ),

    ]
