# Generated by Django 5.1.1 on 2024-11-23 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0010_rename_reason_for_participation_participationdetail_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banned_participants',
            field=models.ManyToManyField(blank=True, related_name='banned_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
